### ISSUE TITLE
Route message to partition by Key CRC

### ISSUE THREAD

**Issue by divan-9** [criteo/kafka-sharp#1] opened 2016-10-03 08:39 UTC
Hello, 
I'm trying to achieve same partition selection behavior as https://github.com/Jroland/kafka-net.
As far as I understand it can be done by implementing IProduceRouter and it looks not trivial.
Another solution is passing partitionId directly but I don't like this option because it doesn't handle changes in topic partitioning.
I can miss something
How do you think, is it possible to customize partition selection with small effort?

**Comment by sdanzan** [comment] 2016-10-07 14:25
What is the strategy? If it's hashing keys and chose partition based on that, you have to pass the partition yourself and you have to be aware of the partitioning scheme. There is no good way to have the driver handle that for you and manage topology changes because it is highly dependant on the application semantics.

**Comment by divan-9** [comment] 2016-10-10 21:25
I did implement solution you have mentioned and it looks OK for my case. 
But as far as I understand there is a periodical metadata request which fires event on metadata changing and I would feel more lucky to have ability to subscribe on this event and change partition selection logic. Or you think it's bad idea?

**Comment by sdanzan** [comment] 2016-10-11 07:30
You have access to the list of partitions for a single topic via the `GetPartitionforTopicAsync` method on `IClusterClient`. You can use it to periodically poll for a list of partitions. Providing event driven interface is something we could provide but that's probably only really useful when implementing an elaborated round robin strategy (i.e. keys are not assigned to fixed partitions).

In the case you're implementing a routing strategy where keys are assigned to fixed partitions, the problem is more complex than just reacting to topology changes because your consumers are probably also taking advantage of the partitioning scheme and need to synchronize if for some reasons the producers decide to route keys to new partitions. Anyway polling periodically for new partitions is probably enough for most cases.

That said, yes we could provide a more comfortable way to access to the current metadata configuration of the cluster, the `GetPartitionforTopicAsync`  is not that much convenient.

**Comment by divan-9** [comment] 2016-10-12 09:43
You are right, now I see that my case is more complex than I have thought. I want to route events for each user session to fixed partition for keeping event processing order, but adding new partition will break this order. It can be harmful in general. Thank you for detailed answer.

**Closed as completed** 2016-10-24 11:20 UTC
